databases:
  - name: game
    databaseName: game_eezf
    user: game_eezf_user

services:
  - type: web
    name: cargame
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: game
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false